# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Steffi Muhanji
email: steffiolesi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Steffi Muhanji, a graduate student at the Thayer School of Engineering at Dartmouth. I am studying energy systems engineering with a research focus in renewable energy integration and demand side management. I hope to work with on electrification in developing countries maybe start a company that aims to bring electricity to rural communities. I would like to use this space to share my knowledge about the energy industry and hopefully start a dialog about some of the social issues surrounding electrification in developing countries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steffiolesi.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  SteffiMuhanji
linkedin_username: Steffi_Muhanji

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock